<?php

use Drupal\Core\Entity\EntityInterface;

function content_hierarchy_install() {

  /** @var \Drupal\Core\Entity\EntityDisplayRepositoryInterface $display_repository */
  $display_repository = \Drupal::service('entity_display.repository');

  // Assign widget settings for the default form mode.

  $existing_node_types = node_type_get_names();
  if(isset($existing_node_types['special_page'])) {
    $entity_form_display = \Drupal::service('entity_display.repository')->getFormDisplay('node', 'special_page', 'default');
    // the function entity_get_form_display is deprecated - replace with the line below, after switching to 8.8
    //$entity_form_display = $display_repository->getFormDisplay('node', 'special_page');
    $entity_form_display->setComponent('field_parent', [
      'type' => 'entity_reference_hierarchy_select'
    ])
      ->save();
  }

  if(isset($existing_node_types['basic_page'])) {
    $entity_form_display = \Drupal::service('entity_display.repository')->getFormDisplay('node', 'basic_page', 'default');
    // the function entity_get_form_display is deprecated - replace with the line below, after switching to 8.8
    //$entity_form_display = $display_repository->getFormDisplay('node', 'special_page');
    $entity_form_display->setComponent('field_parent', [
      'type' => 'entity_reference_hierarchy_select'
    ])
      ->save();
  }

}

function content_hierarchy_uninstall() {

  try {

    $field = \Drupal\field\Entity\FieldConfig::loadByName('node', 'basic_page', 'field_parent');
    if($field) {
      $field->delete();
    }
    $field = \Drupal\field\Entity\FieldConfig::loadByName('node', 'special_page', 'field_parent');
    if($field) {
      $field->delete();
    }
    $field_storage = \Drupal\field\Entity\FieldStorageConfig::loadByName('node', 'field_parent');
    if($field_storage) {
      $field_storage->delete();
    }

  } catch (\Drupal\Core\Entity\EntityStorageException $e) {
    error_log($e->getMessage());
  }

}
