<?php

/**
 * @file
 * Contains merc_content_hierarchy.module.
 */

use Drupal\content_hierarchy\ContentHierarchyUtils;
use Drupal\Core\Cache\Cache;
use Drupal\Core\Entity\ContentEntityInterface;
use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function content_hierarchy_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the content_hierarchy module.
    case 'help.page.content_hierarchy':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Provides the functionality to organize nodes in a tree/hierarchy.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_locale_translation_projects_alter().
 */
function content_hierarchy_locale_translation_projects_alter(&$projects) {
  $module_handler = \Drupal::service('module_handler');
  $path = $module_handler->getModule('content_hierarchy')->getPath();
  $projects['content_hierarchy']['info']['interface translation server pattern'] = $path.'/translations/%language.po';
}

/**
 * Implements hook_theme().
 */
function content_hierarchy_theme() {
  return [
    'content_options' => [
      'variables' => [
        'langcode' => NULL,
        'placement' => -1
      ],
    ],
  ];
}

/**
 * Implements hook_preprocess().
 */
function content_hierarchy_preprocess_content_options(&$variables, $hook) {
  $langcode = $variables['langcode'];
  $placement = $variables['placement'];
  /** @var \Drupal\content_hierarchy\ContentHierarchyWidgets $widgets */
  $widgets = \Drupal::service('content_hierarchy.widgets');
  /** @var \Drupal\content_hierarchy\ContentHierarchyStorage $storage */
  $storage = \Drupal::service('content_hierarchy.storage');
  $variables['items'] = $widgets->getRenderableOptions($langcode, $placement);
  $variables['#cache'] = [
    'tags' => $storage->getListCacheTags($langcode)
  ];
}

/**
 * Implements hook_menu_links_discovered_alter().
 */
function content_hierarchy_menu_links_discovered_alter(&$links) {
  foreach ($links as $id => $link) {
    if (isset($link['parent']) && $link['parent'] == 'system.admin_content') {
      $links[$id]['parent'] = 'content_hierarchy.content_overview';
    }
  }
  if (isset($links['system.admin_content'])) {
    $links['system.admin_content']['parent'] = 'content_hierarchy.content_overview';
    $links['system.admin_content']['weight'] = 101;
    $links['system.admin_content']['title'] = t('All content');
  }
}

/**
 * Implements hook_menu_local_tasks_alter().
 */
function content_hierarchy_menu_local_tasks_alter(&$data, $route_name, \Drupal\Core\Cache\RefinableCacheableDependencyInterface &$cacheability) {
  if (is_array($data) && isset($data['tabs']) && isset($data['tabs'][0]) && isset($data['tabs'][0]['system.admin_content'])) {
    $data['tabs'][0]['system.admin_content']['#weight'] = 101;
    $data['tabs'][0]['system.admin_content']['#link']['title'] = t('All content');
  }
}

/**
 * Implements hook_page_attachments_alter().
 */
function content_hierarchy_page_attachments_alter(array &$page) {
  $user = \Drupal::currentUser();
  if ($user->hasPermission('access toolbar')) {
    $page['#attached']['library'][] = 'content_hierarchy/content_hierarchy';
  }
}

/**
 * Remove content from hierarchy and invalidate tags on entity delete.
 * @param \Drupal\Core\Entity\EntityInterface $entity
 */
function content_hierarchy_entity_delete(Drupal\Core\Entity\EntityInterface $entity) {
  /** @var \Drupal\content_hierarchy\ContentHierarchyStorage $storage */
  $storage = \Drupal::service('content_hierarchy.storage');
  if ($storage->isEntityInHierarchy($entity)) {
    $storage->deleteEntityFromHierarchy($entity);
  }
}

/**
 * Invalidate tag on node delete.
 * @param \Drupal\Core\Entity\EntityInterface $entity
 */
/**
 * Implements hook_entity_insert().
 */
function content_hierarchy_entity_insert(Drupal\Core\Entity\EntityInterface $entity) {
  /** @var \Drupal\content_hierarchy\ContentHierarchyStorage $storage */
  $storage = \Drupal::service('content_hierarchy.storage');
  if ($storage->isEntityInHierarchy($entity)) {
    Cache::invalidateTags(['content_hierarchy_list:' . $entity->language()->getId()]);
  }
}
