<?php
use Drupal\pathauto\Entity\PathautoPattern;

function content_hierarchy_path_install() {
  /** @var \Drupal\content_hierarchy_path\ContentHierarchyPathUpdater $updater */
  $updater = Drupal::service('content_hierarchy_path.updater');
  $updater->updateConfigs();
}

/**
 * Delete old pathauto pattern
 */
function content_hierarchy_path_update_8001() {
  $pattern = PathautoPattern::load('content_hierarchy_pattern');
  if (!is_null($pattern)) {
    $pattern->delete();
  }

  /** @var \Drupal\content_hierarchy_path\ContentHierarchyPathUpdater $updater */
  $updater = Drupal::service('content_hierarchy_path.updater');
  $updater->updateConfigs();
}
